=== Guimove22/M2SITN/recherche_et_gestion_web/tp/TD3_DTD/TD3/Exo 2/Q1/recette.dtd
<!DOCTYPE recette
[
<!ELEMENT recette (nom, portion,preparation,cuisson*,ingredients+,guide) >
<!ELEMENT nom (#PCDATA) >
<!ELEMENT portion (#PCDATA) >

<!ELEMENT preparation (titre) >

<!ELEMENT cuisson (#PCDATA) >
<!ELEMENT ingredients (i+) >
<!ELEMENT i (nom,nombre) >
<!ELEMENT guide (#PCDATA|renvoi|cuisson)* >
<!ELEMENT renvoi (#PCDATA) >



<!ATTLIST article source CDATA #REQUIRED >
<!ATTLIST preparation 
			value CDATA #REQUIRED
			unit CDATA #REQUIRED >
			
<!ATTLIST cuisson 
			value CDATA #REQUIRED
			unit CDATA #REQUIRED>

<!ATTLIST renvoi 
			ref CDATA #REQUIRED>

]>

=== Guimove22/M2SITN/recherche_et_gestion_web/tp/TD3_DTD/TD3/Exo 2/Q3/recette.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE recette SYSTEM "recette.dtd">

<recette>
	<nom>Œufs à la coque</nom>
	<portion>4</portion>
	<preparation value="1" unit="min"/>
	&cuisson;
	<ingredients>
		<i>
			<nom id="ing1">œufs</nom>
			<nbre>4</nbre>
		</i>
	</ingredients>
	&guide;
</recette>

=== Guimove22/M2SITN/recherche_et_gestion_web/tp/TD3_DTD/TD3/Exo 2/Q1/recette.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE recette SYSTEM "recette.dtd">
<recette>
	<nom>Œufs à la coque</nom>
	<portion>4</portion>
	<preparation value="1" unit="min"/>
	<cuisson value="3" unit="min"/>
	<ingredients>
		<i>
			<nom id="ing1">œufs</nom>
			<nbre>4</nbre>
		</i>
	</ingredients>
	<guide>
		Plongez délicatement les
		<renvoi ref="ing1">œufs</renvoi>
		dans de l'eau portée à ébullition. Faîtes reprendre l'ébullition,
		puis baissez le feu et laissez cuire à petits bouillons pendant
		<cuisson value="3" unit="min"/>	minutes. Égouttez les
		<renvoi ref="ing1">oeufs</renvoi>, posez-les dans des coquetiers et 
		coupez horizontalement la partie supérieure pour les déguster.
	</guide>
</recette>
