=== Guimove22/M2SITN/recherche_et_gestion_web/tp/TD3_DTD/TD3/Exo 2/Q2/A/recette.dtd
<!DOCTYPE recette
[
	<!ELEMENT recette (nom, portion,preparation,cuisson*,ingredients+,guide) >
	<!ELEMENT nom (#PCDATA) >
	<!ELEMENT portion (#PCDATA) >
	<!ELEMENT preparation EMPTY >
	<!ELEMENT cuisson EMPTY >
	<!ELEMENT nbre (#PCDATA) >
	<!ELEMENT ingredients (i+) >
	<!ELEMENT i (nom,nombre) >
	<!ELEMENT guide (#PCDATA|renvoi|cuisson)* >
	<!ELEMENT renvoi (#PCDATA) >

	<!ATTLIST nom id ID #IMPLIED >
	<!ATTLIST article source CDATA #REQUIRED >
	
	<!ATTLIST renvoi ref IDREF #REQUIRED>


<!ATTLIST preparation 
			value CDATA #REQUIRED
			unit CDATA #REQUIRED >
			
<!ATTLIST cuisson 
			value CDATA #REQUIRED
			unit CDATA #REQUIRED>


]>

=== Guimove22/M2SITN/recherche_et_gestion_web/tp/TD3_DTD/TD3/Exo 2/Q2/C/td3_exercice3.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE racine SYSTEM "recette.dtd">

<recette>
	<nom>Oeufs a la coque</nom>
	<portion>4</portion>
	<preparation value="1" unit="min"/>
	&cuisson;
	<ingredients>
		<i>
			<nom id="ing1">oeufs</nom>
			<nbre>4</nbre>
		</i>
	</ingredients>
	<guide>
Plongez delicatement les &renvoi; dans de l'eau portee a ebullition. Faites reprendre l'ebullition, puis baissez le feu et laissez cuire a petits bouillons pendant
&cuisson; minutes. Egouttez les &renvoi;, posez-les dans des coquetiers et coupez horizontalement la partie superieure pour les deguster. 
</guide>
</recette>
