<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE recette [

<!ELEMENT recette (nom+, portion,preparation,cuisson*,ingredients+,guide) >
<!ELEMENT nom (#PCDATA) >
<!ELEMENT portion (#PCDATA) >

<!ELEMENT preparation EMPTY >

<!ELEMENT cuisson (#PCDATA) >
<!ELEMENT ingredients (i+) >
<!ELEMENT i (nom,nombre) >
<!ELEMENT guide (#PCDATA|renvoi|cuisson)* >
<!ELEMENT renvoi (#PCDATA) >

<!ENTITY  % PREP_CUI " value  CDATA #REQUIRED  unit (sec|min|h) CDATA #REQUIRED">
<!ATTLIST preparation %PREP_CUI;>

<!ENTITY  VALUE_UNIT "value CDATA #REQUIRED
					 unit (sec|min|h) CDATA #REQUIRED" > 
<!ATTLIST cuisson %VALUE_UNIT; >


<!ATTLIST article source CDATA #REQUIRED >

<!ATTLIST renvoi 
			ref CDATA #REQUIRED>

]>

<recette>
	<nom>Œufs à la coque</nom>
	<portion>4</portion>
	<preparation value="1" unit="min"/>
	<cuisson value="3" unit="min"/>
	<ingredients>
		<i>
			<nom id="ing1">œufs</nom>
			<nbre>4</nbre>
		</i>
	</ingredients>
	<guide>
		Plongez délicatement <renvoi ref="ing1">œufs</renvoi>
		
		dans de l'eau portée à ébullition. Faîtes reprendre l'ébullition,
		puis baissez le feu et laissez cuire à petits bouillons pendant
		<cuisson value="3" unit="min"/> minutes. Égouttez les
		<renvoi ref="ing1">œufs</renvoi>, posez-les dans des coquetiers et 
		coupez horizontalement la partie supérieure pour les déguster.
	</guide>
</recette>